<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;


/**
 * This testing class aims to test the login and register forms.
 * Since those forms are generated by Laravel, we will focus on testing the custom elements (languages)
 */
class UserTest extends TestCase
{
    /**
     * Tries to fill the registery form in different ways
     *
     * @return void
     */
    public function testRegister()
    {
        // Creates an account with no spoken language
        $this->visit('/register')
            ->type("okName", "name")
            ->type("email@sample.com", "email")
            ->type("123", "password")
            ->type("123", "password_confirmation")
            ->press('Register')
            ->seePageIs("/register");

        // Creates a valid account
        // TODO : check() does not seem to work with language...
        // $this->visit('/register')
        //     ->type("okName", "name")
        //     ->type("email@sample.com", "email")
        //     ->type("123", "password")
        //     ->type("123", "password_confirmation")
        //     ->check('language[]')
        //     ->press('Register')
        //     ->seePageIs("/home");

    }
}
